const fs = require('fs');
const path = require('path');
const matter = require('gray-matter');
const puppeteer = require('puppeteer');

const RECIPES_DIR = path.join(process.cwd(), 'content', 'recipes');
const OUTPUT_DIR = path.join(process.cwd(), 'public', 'pdfs');

// Ensure output directory exists
if (!fs.existsSync(OUTPUT_DIR)) {
  fs.mkdirSync(OUTPUT_DIR, { recursive: true });
}

// Simple Markdown Parser for "Manual" look
function parseMarkdown(text) {
  let html = text
    // Protect code blocks (simple version)
    .replace(/```([\s\S]*?)```/g, '<pre class="bg-gray-100 p-4 rounded my-4 overflow-x-auto"><code>$1</code></pre>')
    
    // Headers
    .replace(/^# (.*$)/gm, '<h1 class="text-3xl font-bold mt-8 mb-4 text-slate-900 border-b pb-2">$1</h1>')
    .replace(/^## (.*$)/gm, '<h2 class="text-2xl font-bold mt-6 mb-3 text-slate-800">$1</h2>')
    .replace(/^### (.*$)/gm, '<h3 class="text-xl font-bold mt-4 mb-2 text-slate-700">$1</h3>')
    
    // Formatting
    .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.*?)\*/g, '<em>$1</em>')
    
    // Lists (simple)
    .replace(/^\- (.*$)/gm, '<li class="ml-4">$1</li>')
    
    // Paragraphs (double newline)
    .replace(/\n\n/g, '<br><br>');
    
  // Wrap lists
  html = html.replace(/(<li.*<\/li>)/g, '<ul class="list-disc my-2">$1</ul>');
  // Fix nested lists (hacky but works for visual)
  html = html.replace(/<\/ul><ul class="list-disc my-2">/g, '');

  return html;
}

async function generatePdfs() {
  console.log('🚀 Starting PDF generation...');
  
  const files = fs.readdirSync(RECIPES_DIR).filter(f => f.endsWith('.md'));
  // const testFiles = files.slice(0, 5); 

  console.log(`Found ${files.length} recipes. Starting batch generation...`);

  const browser = await puppeteer.launch({ headless: "new" });
  const page = await browser.newPage();
  
  let sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">`;

  const SITE_URL = 'https://realaiexamples.com';
  const currentDate = new Date().toISOString();

  for (let i = 0; i < files.length; i++) {
    const file = files[i];
    const filePath = path.join(RECIPES_DIR, file);
    const rawContent = fs.readFileSync(filePath, 'utf8');
    const { data, content } = matter(rawContent);
    const slug = file.replace('.md', '');

    const htmlContent = parseMarkdown(content);
    
    const htmlTemplate = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8">
        <script src="https://cdn.tailwindcss.com"></script>
        <style>
            @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;800&display=swap');
            body { font-family: 'Inter', sans-serif; -webkit-print-color-adjust: exact; }
            @page { margin: 20mm; }
        </style>
      </head>
      <body class="bg-white text-slate-900 max-w-3xl mx-auto">
        
        <!-- Cover Page style header -->
        <div class="mb-12 border-b-2 border-slate-900 pb-6">
            <div class="uppercase tracking-widest text-xs font-bold text-slate-500 mb-2">Real AI Examples</div>
            <h1 class="text-4xl font-extrabold text-slate-900 mb-2">${data.title}</h1>
            <p class="text-xl text-slate-600">${data.tagline || ''}</p>
            
            <div class="flex gap-4 mt-6 text-sm font-mono text-slate-500">
                <span class="bg-slate-100 px-2 py-1 rounded">Category: ${data.category}</span>
                <span class="bg-slate-100 px-2 py-1 rounded">Time: ${data.time}</span>
                <span class="bg-slate-100 px-2 py-1 rounded">Difficulty: ${data.difficulty}</span>
            </div>
        </div>

        <!-- Content -->
        <div class="prose prose-slate max-w-none">
            ${htmlContent}
        </div>

        <!-- Footer -->
        <div class="mt-16 pt-8 border-t border-slate-200 text-center text-slate-400 text-sm">
            <p>Generated by RealAIExamples.com • The Agency Cookbook</p>
            <p>Find more automation blueprints at https://realaiexamples.com</p>
        </div>

      </body>
      </html>
    `;

    await page.setContent(htmlTemplate, { waitUntil: 'load' });
    
    await page.pdf({
      path: path.join(OUTPUT_DIR, `${slug}.pdf`),
      format: 'A4',
      printBackground: true,
      displayHeaderFooter: false,
      margin: { top: '20mm', bottom: '20mm', left: '20mm', right: '20mm' }
    });
    
    // Add to sitemap
    sitemap += `
  <url>
    <loc>${SITE_URL}/pdfs/${slug}.pdf</loc>
    <lastmod>${currentDate}</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.8</priority>
  </url>`;

    if ((i + 1) % 50 === 0) {
        console.log(`...Processed ${i + 1}/${files.length} PDFs`);
    }
  }

  sitemap += `\n</urlset>`;
  fs.writeFileSync(path.join(process.cwd(), 'public', 'sitemap-pdfs.xml'), sitemap);
  console.log('✅ Generated public/sitemap-pdfs.xml');

  await browser.close();
  console.log('✨ PDF Generation Complete!');
}

generatePdfs();
