const fs = require('fs');
const path = require('path');
const matter = require('gray-matter');
const { execSync } = require('child_process');

const RECIPES_DIR = path.join(__dirname, '../content/recipes');
const OUTPUT_DIR = path.join(__dirname, '../public/downloads/skills');
const TEMP_DIR = path.join(__dirname, '../temp_skills');
const PACKAGE_SCRIPT = '/home/akhilnairmk/.npm-global/lib/node_modules/@google/gemini-cli/node_modules/@google/gemini-cli-core/dist/src/skills/builtin/skill-creator/scripts/package_skill.cjs';

// Ensure output and temp dirs exist
if (!fs.existsSync(OUTPUT_DIR)) fs.mkdirSync(OUTPUT_DIR, { recursive: true });
if (fs.existsSync(TEMP_DIR)) fs.rmSync(TEMP_DIR, { recursive: true, force: true });
fs.mkdirSync(TEMP_DIR);

const recipes = fs.readdirSync(RECIPES_DIR).filter(f => f.endsWith('.md'));

console.log(`🚀 Starting Skill Factory for ${recipes.length} recipes...`);

recipes.forEach(file => {
    try {
        const filePath = path.join(RECIPES_DIR, file);
        const content = fs.readFileSync(filePath, 'utf8');
        const { data, content: body } = matter(content);

        if (!data.id || !data.description) {
            console.warn(`⚠️ Skipping ${file}: Missing ID or Description`);
            return;
        }

        const skillName = data.id;
        const skillFolderPath = path.join(TEMP_DIR, skillName);
        fs.mkdirSync(skillFolderPath);

        // 1. Create SKILL.md for Gemini CLI
        // Extract the prompt logic. If there's a "# Prompt" section, use it.
        // Otherwise, use the Workflow section.
        let skillLogic = '';
        if (body.includes('# Prompt')) {
            skillLogic = body.split('# Prompt')[1].trim();
        } else if (body.includes('## Workflow')) {
            skillLogic = body.split('## Workflow')[1].trim();
        } else {
            skillLogic = body.trim();
        }

        const skillMd = `---
name: ${skillName}
description: ${data.description.replace(/\n/g, ' ')}
---

# ${data.title}

${skillLogic}
`;

        fs.writeFileSync(path.join(skillFolderPath, 'SKILL.md'), skillMd);

        // 2. Package for Gemini CLI (.skill)
        try {
            execSync(`node ${PACKAGE_SCRIPT} ${skillFolderPath} ${OUTPUT_DIR}`);
            console.log(`✅ Packaged Gemini Skill: ${skillName}`);
        } catch (err) {
            console.error(`❌ Failed to package Gemini Skill ${skillName}:`, err.message);
        }

        // 3. Create Claude Code "Tool" (.md file)
        const claudeMd = `# Claude Code Agent: ${data.title}

## Description
${data.description}

## Instructions
${skillLogic}

---
*Generated by Real AI Examples Skill Factory*
`;
        fs.writeFileSync(path.join(OUTPUT_DIR, `${skillName}-claude.md`), claudeMd);
        console.log(`✅ Created Claude Instruction: ${skillName}-claude.md`);

        // 4. Create Cursor Rule (.cursorrules file)
        const cursorRule = `---
description: ${data.description.replace(/\n/g, ' ')}
globs: 
---

# ${data.title} Cursor Rule

You are an expert AI agent. Your mission is to follow this specific workflow:

${skillLogic}

## Guidelines for Cursor
- Always follow the Phase 1, 2, 3 structure provided above.
- Use terminal commands when necessary to process files.
- If input files are missing, use the sampleData logic to seed them.

*Generated by Real AI Examples Skill Factory*
`;
        fs.writeFileSync(path.join(OUTPUT_DIR, `${skillName}.cursorrules`), cursorRule);
        console.log(`✅ Created Cursor Rule: ${skillName}.cursorrules`);

    } catch (error) {
        console.error(`❌ Error processing ${file}:`, error.message);
    }
});

// Cleanup temp folder
fs.rmSync(TEMP_DIR, { recursive: true, force: true });
console.log('✨ Skill Factory complete!');
